export const MenuIcons = [
  'address-book', 'address-book-o', 'address-card', 'address-card-o',
  'adjust', 'american-sign-language-interpreting', 'anchor', 'archive',
  'area-chart', 'arrows', 'arrows-h', 'arrows-v', 'assistive-listening-systems',
  'asterisk', 'at', 'audio-description', 'balance-scale', 'ban',
  'bar-chart', 'barcode', 'bars', 'bath', 'battery-empty', 'battery-full',
  'battery-half', 'battery-quarter', 'battery-three-quarters',
  'bed', 'beer', 'bell', 'bell-o', 'bell-slash', 'bell-slash-o',
  'bicycle', 'binoculars', 'birthday-cake', 'blind', 'bluetooth',
  'bluetooth-b', 'bolt', 'bomb', 'book', 'bookmark', 'bookmark-o',
  'braille', 'briefcase', 'bug', 'building', 'building-o', 'bullhorn',
  'bullseye', 'bus', 'calculator', 'calendar', 'calendar-check-o',
  'calendar-minus-o', 'calendar-o', 'calendar-plus-o', 'calendar-times-o',
  'camera', 'camera-retro', 'car', 'caret-square-o-down', 'caret-square-o-left',
  'caret-square-o-right', 'caret-square-o-up', 'cart-arrow-down',
  'cart-plus', 'cc', 'certificate', 'check', 'check-circle', 'check-circle-o',
  'check-square', 'check-square-o', 'child', 'circle', 'circle-o', 'circle-o-notch',
  'circle-thin', 'clock-o', 'clone', 'cloud', 'cloud-download', 'cloud-upload',
  'code', 'code-fork', 'coffee', 'cog', 'cogs', 'comment', 'comment-o',
  'commenting', 'commenting-o', 'comments', 'comments-o', 'compass',
  'copyright', 'creative-commons', 'credit-card', 'credit-card-alt', 'crop',
  'crosshairs', 'cube', 'cubes', 'cutlery', 'database', 'deaf', 'desktop',
  'diamond', 'dot-circle-o', 'download', 'ellipsis-h', 'ellipsis-v',
  'envelope', 'envelope-o', 'envelope-open', 'envelope-open-o', 'envelope-square',
  'eraser', 'exchange', 'exclamation', 'exclamation-circle',
  'exclamation-triangle', 'external-link', 'external-link-square', 'eye',
  'eye-slash', 'eyedropper', 'fax', 'female', 'fighter-jet', 'file-archive-o',
  'file-audio-o', 'file-code-o', 'file-excel-o', 'file-image-o', 'file-pdf-o',
  'file-powerpoint-o', 'file-video-o', 'file-word-o', 'film', 'filter', 'fire',
  'fire-extinguisher', 'flag', 'flag-checkered', 'flag-o', 'flask', 'folder',
  'folder-o', 'folder-open', 'folder-open-o', 'frown-o', 'futbol-o', 'gamepad',
  'gavel', 'gift', 'glass', 'globe', 'graduation-cap', 'hand-lizard-o',
  'hand-paper-o', 'hand-peace-o', 'hand-pointer-o', 'hand-rock-o',
  'hand-scissors-o', 'hand-spock-o', 'handshake-o', 'hashtag', 'hdd-o',
  'headphones', 'heart', 'heart-o', 'heartbeat', 'history', 'home', 'hourglass',
  'hourglass-end', 'hourglass-half', 'hourglass-o', 'hourglass-start',
  'i-cursor', 'id-badge', 'id-card', 'id-card-o', 'inbox', 'industry', 'info',
  'info-circle', 'key', 'keyboard-o', 'language', 'laptop', 'leaf', 'lemon-o',
  'level-down', 'level-up', 'life-ring', 'lightbulb-o', 'line-chart', 'location-arrow',
  'lock', 'low-vision', 'magic', 'magnet', 'male', 'map', 'map-marker',
  'map-o', 'map-pin', 'map-signs', 'meh-o', 'microchip', 'microphone',
  'microphone-slash', 'minus', 'minus-circle', 'minus-square', 'minus-square-o',
  'mobile', 'money', 'moon-o', 'motorcycle', 'mouse-pointer', 'music',
  'newspaper-o', 'object-group', 'object-ungroup', 'paint-brush', 'paper-plane',
  'paper-plane-o', 'paw', 'pencil', 'pencil-square', 'pencil-square-o',
  'percent', 'phone', 'phone-square', 'picture-o', 'pie-chart', 'plane',
  'plug', 'plus', 'plus-circle', 'plus-square', 'plus-square-o', 'podcast',
  'power-off', 'print', 'puzzle-piece', 'qrcode', 'question', 'question-circle',
  'question-circle-o', 'quote-left', 'quote-right', 'random', 'recycle',
  'refresh', 'registered', 'reply', 'reply-all', 'retweet', 'road', 'rocket',
  'rss', 'rss-square', 'search', 'search-minus', 'search-plus', 'server',
  'share', 'share-alt', 'share-alt-square', 'share-square', 'share-square-o',
  'shield', 'ship', 'shopping-bag', 'shopping-basket', 'shopping-cart',
  'shower', 'sign-in', 'sign-language', 'sign-out', 'signal', 'sitemap',
  'sliders', 'smile-o', 'snowflake-o', 'sort', 'sort-alpha-asc', 'sort-alpha-desc',
  'sort-amount-asc', 'sort-amount-desc', 'sort-asc', 'sort-desc',
  'sort-numeric-asc', 'sort-numeric-desc', 'space-shuttle', 'spinner',
  'spoon', 'square', 'square-o', 'star', 'star-half', 'star-half-o',
  'star-o', 'sticky-note', 'sticky-note-o', 'street-view', 'suitcase',
  'sun-o', 'tablet', 'tachometer', 'tag', 'tags', 'tasks', 'taxi',
  'television', 'terminal', 'thermometer-empty', 'thermometer-full',
  'thermometer-half', 'thermometer-quarter', 'thermometer-three-quarters',
  'thumb-tack', 'thumbs-down', 'thumbs-o-down', 'thumbs-o-up', 'thumbs-up',
  'ticket', 'times', 'times-circle', 'times-circle-o', 'tint', 'toggle-off',
  'toggle-on', 'trademark', 'trash', 'trash-o', 'tree', 'trophy', 'truck',
  'tty', 'umbrella', 'universal-access', 'university', 'unlock', 'unlock-alt',
  'upload', 'user', 'user-circle', 'user-circle-o', 'user-o', 'user-plus',
  'user-secret', 'user-times', 'users', 'video-camera', 'volume-control-phone',
  'volume-down', 'volume-off', 'volume-up', 'wheelchair', 'wheelchair-alt',
  'wifi', 'window-close', 'window-close-o', 'window-maximize',
  'window-minimize', 'window-restore', 'wrench'];
